#!/usr/bin/env bash
# Script that installs and configure HAProxy on lb-01 server
# Config. of HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Ensure that HAProxy can be managed via an init script

# Installation and config HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  itechpluscliq_frontend
        bind *:80
        mode http
        default_backend itechpluscliq_backend
backend itechpluscliq_backend
        balance roundrobin
	server 315130-web-01 18.208.119.80:80 check
	server 315130-web-02 54.162.225.50:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
